# Generated by Django 3.1.2 on 2021-06-09 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210609_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='worker',
        ),
        migrations.AddField(
            model_name='news',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
